### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by andrewdavidmackenzie**

### CODE REVIEW

**Comment by guybedford** [comment]
License at https://github.com/substack/path-browserify/blob/master/LICENSE.

**Comment by guybedford** [comment]
Sorry pasted the wrong project, the one above is for the path repo.

This project can just use a standard copyrightless MIT as it's one of the only ones that is custom code.

Thanks I know these are a lot to check... that's exactly why I've been weary of it!

**Comment by andrewdavidmackenzie** [comment]
Will that change do it?

**Comment by guybedford** [comment]
Added in 38bd437.

**Pull request closed without merging**
